CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('ADMIN', 'AGENT'))
);

CREATE TABLE IF NOT EXISTS fields (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  crop_type TEXT NOT NULL,
  planting_date DATE NOT NULL,
  stage TEXT NOT NULL CHECK (stage IN ('PLANTED', 'GROWING', 'READY', 'HARVESTED')),
  assigned_agent_id UUID REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS field_updates (
  id UUID PRIMARY KEY,
  field_id UUID NOT NULL REFERENCES fields(id) ON DELETE CASCADE,
  agent_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  note TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
